name: API Tests

permissions:
  contents: write    
  pages: write
  id-token: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install Newman + Reporter
      run: npm install -g newman newman-reporter-htmlextra

    - name: Run Jikan tests
      run: |
        newman run postman-tests/collections/jikan_testes_QA.postman_collection.json \
          -e postman-tests/environments/jikan_kitsu_testing.postman_environment.json \
          -r htmlextra \
          --reporter-htmlextra-export postman-tests/reports/resultado_jikan.html

    - name: Run Kitsu tests
      run: |
        newman run postman-tests/collections/kitsu_testes_exploratorios.postman_collection.json \
          -e postman-tests/environments/jikan_kitsu_testing.postman_environment.json \
          -r htmlextra \
          --reporter-htmlextra-export postman-tests/reports/resultado_kitsu.html

    - name: Move reports to repository folder
      run: |
        mkdir -p relatorios
        cp postman-tests/reports/resultado_jikan.html relatorios/
        cp postman-tests/reports/resultado_kitsu.html relatorios/

    - name: Commit updated reports
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add relatorios/
        git commit -m "Atualiza relatórios" || echo "Nenhuma mudança para commitar"
        git push

